Support custom route methods && uniswap v3 multi hop
joshstevens19/simple-uniswap-sdk pull request #45
Opened 2022-06-28 03:17 UTC by liu-zhipeng

- [ ] support custom router abi (For Pangolin and Trader Joe swap on avalanche)
- [ ] support custom router method names
- [ ] support uniswap v3 multihop
- [ ] fix some issues

2022-06-29 17:37 UTC, liu-zhipeng commented
Hi. I am so excited to contribute to such a great project. I found some small problems while using uniswap sdk. For example, some uniswap forked dexs like pangolin swap changed router functions. especially ETH to AVAX. So i added some changes for developers to use custom router abi and router methods. Also I added some code to support uniswap v3 multihop. I would like you to review my changes if you have time. Thank you again for a great sdk!

2022-06-29 17:58 UTC, joshstevens19 commented
Hey @liu-zhipeng firstly thanks so much for this!! Help from others is needed and this looks incredible already. 

Only scanned on phone but 1 thing which popped out any new things or featured you added to this please add to the readme doc, for example you done some liquidity work and now supporting multihop adding to the docs is the last part missing I think! 

I will review this tomorrow be great to review with the docs update as well thanks a lot hope this will be your first of many PRs 💪

2022-06-29 18:09 UTC, liu-zhipeng commented
> Hey @liu-zhipeng firstly thanks so much for this!! Help from others is needed and this looks incredible already.
> 
> Only scanned on phone but 1 thing which popped out any new things or featured you added to this please add to the readme doc, for example you done some liquidity work and now supporting multihop adding to the docs is the last part missing I think!
> 
> I will review this tomorrow be great to review with the docs update as well thanks a lot hope this will be your first of many PRs 💪

2022-06-30 09:50 UTC, savasadar approved these changes

2022-06-30 16:45 UTC, joshstevens19 commented on README.md
> +    liquidityProviderFee: number[];
doesn't seem correct here as in v2 it would still be string

2022-06-30 16:46 UTC, joshstevens19 commented on README.md
> +  liquidityProviderFeePercent: [0.003, 0.005, 0.003],
from my memory the liquidity provider fee percent on this level is just 1 percent and if you got many routes you can go then it many objects in the array

2022-06-30 16:46 UTC, joshstevens19 commented on README.md
> +  liquidityProviderFee: ['0.030000000000000000','0.050000000000000000','0.030000000000000000'],
same as below

2022-06-30 16:46 UTC, joshstevens19 commented on README.md
> +        liquidityProviderFee: [0.003, 0.003],
breaking change for v2...

2022-06-30 16:48 UTC, joshstevens19 commented on README.md
> +        liquidityProviderFee: [0.003, 0.005, 0.003],
if your getting a quote as it is now it picks them best price but also factor in the provider fee i would probably expect 3 rows in this case no?

2022-06-30 16:48 UTC, joshstevens19 commented on src/common/utils/is-same-address.spec.ts
> +  it('should return true if its a valid ethereum address type', () => {
change descriptions of test

2022-06-30 16:48 UTC, joshstevens19 commented on src/common/utils/is-same-address.spec.ts
> +  it('should return false when one of them is a invalid address', () => {
same

2022-06-30 16:48 UTC, joshstevens19 commented on src/common/utils/is-same-address.spec.ts
> +    expect(isSameAddress('0x0', '0x1')).toEqual(false);
same

2022-06-30 16:49 UTC, joshstevens19 commented on src/factories/pair/models/current-trade-context.ts
> +  liquidityProviderFee: string[];
need to have a bigger discussion here should be 1 object per liquidity provider fee i think... and the top one have the best one! the idea is the quote gives you everything you need to execute the trade

2022-06-30 16:50 UTC, joshstevens19 commented on src/factories/pair/models/trade-context.ts
> +  liquidityProviderFeePercent: number[];
again arrays here v2 wont be an array

2022-06-30 16:50 UTC, joshstevens19 commented on src/factories/pair/uniswap-pair.factory.ts
> +      liquidityProviderFee: bestRouteQuote.liquidityProviderFee.map((f) =>
breaking changes for v2.. if many liquidity provider fees the expected convert quote will be different depending on that no? would not expect a loop here i dont think...

2022-06-30 16:51 UTC, joshstevens19 commented on src/factories/pair/uniswap-pair.factory.ts
> +      liquidityProviderFee: bestRouteQuote.liquidityProviderFee.map((f) =>
same as above

2022-06-30 16:51 UTC, joshstevens19 commented on src/factories/pair/uniswap-pair.factory.ts
> +      liquidityProviderFee: bestRouteQuote.liquidityProviderFee.map((f) =>
same as above

2022-06-30 16:52 UTC, joshstevens19 commented on src/factories/router/models/token-routes.ts
> +    fromTokenPairs?: Pool[] | undefined;
what about v2 support?

2022-07-11 08:41 UTC, mburger81 commented
@joshstevens19 @liu-zhipeng 
when do you think you can find a solution for the changes requested and release this?

2022-07-11 08:44 UTC, liu-zhipeng commented
> @joshstevens19 @liu-zhipeng when do you think you can find a solution for the changes requested and release this?

Once @joshstevens19  confirms this, we can release this, cus all features are working properly now.

2022-07-11 08:52 UTC, liu-zhipeng commented
That is no problem at all to return `liquidityProviderFee` as array. If there is some issues on the apps which are using old version. they MUST update to support uniswap v3. Because each uniswap V3 pairs have 3 different fee tiers.
I am waiting for @joshstevens19 's reivew yet.

2022-07-14 03:41 UTC, liu-zhipeng commented
This PR should be closed? @joshstevens19

2022-07-14 12:16 UTC, joshstevens19 commented
No PR is good sorry been away I’m going to get to this soon!

2022-07-27 04:59 UTC, mburger81 commented
@liu-zhipeng why did you close this unmerged?

2022-08-01 14:56 UTC, helios8090 commented on README.md
> +  liquidityProviderFee: string[];
in v2 `liquidityProviderFee` should be array in this version

2022-08-01 14:56 UTC, helios8090 commented on README.md
> +  liquidityProviderFee: string[];
@liu-zhipeng am i correct?

2022-08-01 14:58 UTC, helios8090 commented
when will you release this? @liu-zhipeng

2022-08-01 17:21 UTC, mburger81 commented
@helios8090 the problem is, @liu-zhipeng can not do the merge and the release
@joshstevens19 sorry dude but its really annoying :(

2022-08-01 18:20 UTC, liu-zhipeng commented
> @helios8090 the problem is, @liu-zhipeng can not do the merge and the release @joshstevens19 sorry dude but its really annoying :(

I have no permission to merge.

2022-08-01 19:57 UTC, mburger81 commented
@liu-zhipeng I know, for that reason I asked you to fork, merge and release your own repository, just temporally until @joshstevens19 will merge it

we are trying to make webcomponents for the community using simple-uniswap to deliver a well working, free, fast, working everywhere solution
but we are stuck on waiting this merge since e 5 weeks

2022-08-01 20:08 UTC, joshstevens19 commented
Guys super sorry I’ve been away and it’s super hard for me to see these sometimes. The main problem with the PR is it’s a breaking interface change to the liquidity interface which means if we release it everyones integration will break who use to think that was a string. I’m going to set a note for tomorrow AM before I do anything else to do another PR review on this. I did do a PR review but the things I asked still is missing. We can’t do breaking changes in the interface we can ofc add a new field and depreciate the old one for v1 and v2 use only but if you could make it so v2 interface is NONE breaking then I’m happy to get this in asap @liu-zhipeng

2022-08-01 20:09 UTC, joshstevens19 commented
Remind me set.. tomorrow AM 9:45 BST! will do another review of it and highlight the main issues. Sorry for the delay!

2022-08-01 21:58 UTC, mburger81 commented
Yeah that was what I'm saying, there is this breaking change you already told us
for that reason I was wondering why you wrote later, anything is fine, because it isn't

I Just ask you to maybe integrate this changes also on the swap ui you provide

THX a lot!

2022-08-01 22:05 UTC, joshstevens19 commented
Well it is - you just expose the field in a new property in the interface and write docs around it why, it’s a very easy fix in this PR!

2022-08-01 22:07 UTC, joshstevens19 requested changes

2022-08-01 22:07 UTC, joshstevens19 commented on src/factories/pair/models/current-trade-context.ts
> +  liquidityProviderFee: string[];
This here! This needs to be a new field if it has to be an array so it doesn’t do a breaking change to the interface

2022-08-01 22:07 UTC, joshstevens19 commented on src/factories/pair/models/trade-context.ts
> +  liquidityProviderFeePercent: number[];
Same as above breaking change in the trade context ..

2022-08-02 06:03 UTC, mburger81 commented
@liu-zhipeng nice!

2022-08-02 08:50 UTC, joshstevens19 commented
this looks better @liu-zhipeng can you just update the readme docs to show the new field and explain it so people understand?

2022-08-02 11:42 UTC, liu-zhipeng commented
> I have already updated readme.

2022-08-02 11:44 UTC, liu-zhipeng commented
https://github.com/joshstevens19/simple-uniswap-sdk/pull/45/commits/7a178a7e9618ef32258b2e6daaa8d076189f183d

2022-08-03 13:04 UTC, joshstevens19 approved these changes
need to run 1 manual test later if good will merge and deploy.. thanks for doing this and sorry it ended up taking longer then we wanted. @liu-zhipeng your a legend!

2022-08-03 13:07 UTC, liu-zhipeng commented
Thank you for your approval. @joshstevens19  And I am super happy if my work can be helpful for others.

2022-08-03 23:58 UTC, joshstevens19 commented
@liu-zhipeng so done manually tests everything about done just one thing I spotted is when on a v2 trade the `liquidityProviderFeesV3` is populated it should be an empty array [] could you do that then we can merge and deploy!


<img width="288" alt="image" src="https://user-images.githubusercontent.com/18472422/182733942-e481a578-8f86-4ba6-ab7c-c90daed91b5f.png">

2022-08-04 00:54 UTC, liu-zhipeng commented
> @liu-zhipeng so done manually tests everything works well, just one thing I spotted is when on a v2 trade the `liquidityProviderFeesV3` is populated it should be an empty array [] could you do that then we can merge and deploy!
> 
> <img alt="image" width="288" src="https://user-images.githubusercontent.com/18472422/182733942-e481a578-8f86-4ba6-ab7c-c90daed91b5f.png">

I thought that was more consistent. anyway updated finally!

2022-08-04 01:03 UTC, merged

2022-08-04 01:03 UTC, joshstevens19 commented
amazing! Will deploy tomorrow @liu-zhipeng thanks again

2022-08-04 01:11 UTC, liu-zhipeng commented
Awesome!

2022-08-04 09:04 UTC, joshstevens19 commented
https://github.com/joshstevens19/simple-uniswap-sdk/releases/tag/3.7.0 - its now deployed